version: "3"
services:
  mongo:
    image: mongo
    networks:
      - smartnet

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - smartnet

    hostname: "smartmq"

  bids:
    image: fsalehpour/bids:latest
    restart: on-failure
    networks:
      - smartnet
    environment:
      - RMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  smart:
    restart: on-failure
    build: .
    networks:
      - smartnet
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - ../reports:/reports

networks:
  smartnet: